---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
suites:
- name: disable
  run_list:
    - recipe[apparmor]
    - recipe[minitest-handler]
- name: enable
  run_list:
     - recipe[apparmor]
     - recipe[minitest-handler]
  attributes:
    apparmor:
      disable: false
